LOCAL_CPP_EXTENSION := .cc

LOCAL_SRC_FILES := \
	base/asyncfile.cc \
	base/asynchttprequest.cc \
	base/asyncsocket.cc \
	base/asynctcpsocket.cc \
	base/asyncudpsocket.cc \
	base/autodetectproxy.cc \
	base/bandwidthsmoother.cc \
	base/base64.cc \
	base/basicpacketsocketfactory.cc \
	base/bytebuffer.cc \
	base/checks.cc \
	base/common.cc \
	base/cpumonitor.cc \
	base/crc32.cc \
	base/diskcache.cc \
	base/event.cc \
	base/filelock.cc \
	base/fileutils.cc \
	base/firewallsocketserver.cc \
	base/flags.cc \
	base/helpers.cc \
	base/host.cc \
	base/httpbase.cc \
	base/httpclient.cc \
	base/httpcommon.cc \
	base/httprequest.cc \
	base/httpserver.cc \
	base/ipaddress.cc \
	base/json.cc \
	base/logging.cc \
	base/md5.cc \
	base/messagedigest.cc \
	base/messagehandler.cc \
	base/messagequeue.cc \
	base/multipart.cc \
	base/natserver.cc \
	base/natsocketfactory.cc \
	base/nattypes.cc \
	base/nethelpers.cc \
	base/network.cc \
	base/nssidentity.cc \
	base/nssstreamadapter.cc \
	base/optionsfile.cc \
	base/pathutils.cc \
	base/physicalsocketserver.cc \
	base/proxydetect.cc \
	base/proxyinfo.cc \
	base/proxyserver.cc \
	base/ratelimiter.cc \
	base/ratetracker.cc \
	base/sha1.cc \
	base/sharedexclusivelock.cc \
	base/signalthread.cc \
	base/socketadapters.cc \
	base/socketaddress.cc \
	base/socketaddresspair.cc \
	base/socketpool.cc \
	base/socketstream.cc \
	base/ssladapter.cc \
	base/sslsocketfactory.cc \
	base/sslidentity.cc \
	base/sslstreamadapter.cc \
	base/sslstreamadapterhelper.cc \
	base/stream.cc \
	base/stringencode.cc \
	base/stringutils.cc \
	base/systeminfo.cc \
	base/task.cc \
	base/taskparent.cc \
	base/taskrunner.cc \
	base/testclient.cc \
	base/thread.cc \
	base/timeutils.cc \
	base/timing.cc \
	base/transformadapter.cc \
	base/urlencode.cc \
	base/versionparsing.cc \
	base/virtualsocketserver.cc \
	base/worker.cc \
	xmllite/qname.cc \
	xmllite/xmlbuilder.cc \
	xmllite/xmlconstants.cc \
	xmllite/xmlelement.cc \
	xmllite/xmlnsstack.cc \
	xmllite/xmlparser.cc \
	xmllite/xmlprinter.cc \
	xmpp/chatroommoduleimpl.cc \
	xmpp/constants.cc \
	xmpp/discoitemsquerytask.cc \
	xmpp/hangoutpubsubclient.cc \
	xmpp/iqtask.cc \
	xmpp/jid.cc \
	xmpp/moduleimpl.cc \
	xmpp/mucroomconfigtask.cc \
	xmpp/mucroomdiscoverytask.cc \
	xmpp/mucroomlookuptask.cc \
	xmpp/mucroomuniquehangoutidtask.cc \
	xmpp/pingtask.cc \
	xmpp/presenceouttask.cc \
	xmpp/presencereceivetask.cc \
	xmpp/presencestatus.cc \
	xmpp/pubsubclient.cc \
	xmpp/pubsub_task.cc \
	xmpp/pubsubtasks.cc \
	xmpp/receivetask.cc \
	xmpp/rostermoduleimpl.cc \
	xmpp/saslmechanism.cc \
	xmpp/xmppclient.cc \
	xmpp/XmppSession.cc \
	xmpp/xmpplogininterface.cc \
	xmpp/xmppengineimpl.cc \
	xmpp/xmpplocalengine.cc \
	xmpp/xmpplocallogintask.cc \
	xmpp/xmppengineimpl_iq.cc \
	xmpp/xmpplogintask.cc \
	xmpp/xmpploginhandler.cc \
	xmpp/xmppregistrationtask.cc \
	xmpp/xmppstanzaparser.cc \
	xmpp/xmpptask.cc \
	xmpp/xmppauth.cc \
	xmpp/xmpppump.cc \
	xmpp/xmppsocket.cc \
	xmpp/xmppthread.cc \
	base/ifaddrs-android.cc \
	base/linux.cc \
	base/latebindingsymboltable.cc \
	base/openssladapter.cc \
	base/openssldigest.cc \
	base/opensslidentity.cc \
	base/opensslstreamadapter.cc \
	base/posix.cc \
	base/unixfilesystem.cc \

