# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libjingle
DEFS_Debug := \
	'-DEXPAT_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_VOICEMAIL' \
	'-DGTEST_RELATIVE_PATH' \
	'-DJSONCPP_RELATIVE_PATH' \
	'-DLOGGING=1' \
	'-DSRTP_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_SSL' \
	'-DFEATURE_ENABLE_PSTN' \
	'-DHAVE_SRTP' \
	'-DHAVE_WEBRTC_VIDEO' \
	'-DHAVE_WEBRTC_VOICE' \
	'-DUSE_WEBRTC_DEV_BRANCH' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DHASH_NAMESPACE=__gnu_cxx' \
	'-DPOSIX' \
	'-DDISABLE_DYNAMIC_CAST' \
	'-DHAVE_OPENSSL_SSL_H=1' \
	'-D_REENTRANT' \
	'-DXML_STATIC' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DHAVE_SYS_UIO_H' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	--sysroot=/home/richard/android-sdk/android-ndk-r8d/platforms/android-9/arch-arm \
	-I/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/stlport/stlport \
	-I/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/gnu-libstdc++/4.6/include \
	-Os \
	-g \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated \
	-Wno-abi

INCS_Debug := \
	-I. \
	-Ithird_party \
	-Ithird_party/webrtc \
	-Ithird_party/expat/files/lib \
	-Ithird_party/jsoncpp/overrides/include \
	-Ithird_party/jsoncpp/source/include \
	-Ithird_party/openssl/openssl/include

DEFS_Release := \
	'-DEXPAT_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_VOICEMAIL' \
	'-DGTEST_RELATIVE_PATH' \
	'-DJSONCPP_RELATIVE_PATH' \
	'-DLOGGING=1' \
	'-DSRTP_RELATIVE_PATH' \
	'-DFEATURE_ENABLE_SSL' \
	'-DFEATURE_ENABLE_PSTN' \
	'-DHAVE_SRTP' \
	'-DHAVE_WEBRTC_VIDEO' \
	'-DHAVE_WEBRTC_VOICE' \
	'-DUSE_WEBRTC_DEV_BRANCH' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DHASH_NAMESPACE=__gnu_cxx' \
	'-DPOSIX' \
	'-DDISABLE_DYNAMIC_CAST' \
	'-DHAVE_OPENSSL_SSL_H=1' \
	'-D_REENTRANT' \
	'-DXML_STATIC' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DHAVE_SYS_UIO_H' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	--sysroot=/home/richard/android-sdk/android-ndk-r8d/platforms/android-9/arch-arm \
	-I/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/stlport/stlport \
	-I/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/gnu-libstdc++/4.6/include \
	-Os \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-fomit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated \
	-Wno-abi

INCS_Release := \
	-I. \
	-Ithird_party \
	-Ithird_party/webrtc \
	-Ithird_party/expat/files/lib \
	-Ithird_party/jsoncpp/overrides/include \
	-Ithird_party/jsoncpp/source/include \
	-Ithird_party/openssl/openssl/include

OBJS := \
	$(obj).target/$(TARGET)/talk/base/asyncfile.o \
	$(obj).target/$(TARGET)/talk/base/asynchttprequest.o \
	$(obj).target/$(TARGET)/talk/base/asyncsocket.o \
	$(obj).target/$(TARGET)/talk/base/asynctcpsocket.o \
	$(obj).target/$(TARGET)/talk/base/asyncudpsocket.o \
	$(obj).target/$(TARGET)/talk/base/autodetectproxy.o \
	$(obj).target/$(TARGET)/talk/base/bandwidthsmoother.o \
	$(obj).target/$(TARGET)/talk/base/base64.o \
	$(obj).target/$(TARGET)/talk/base/basicpacketsocketfactory.o \
	$(obj).target/$(TARGET)/talk/base/bytebuffer.o \
	$(obj).target/$(TARGET)/talk/base/checks.o \
	$(obj).target/$(TARGET)/talk/base/common.o \
	$(obj).target/$(TARGET)/talk/base/cpumonitor.o \
	$(obj).target/$(TARGET)/talk/base/crc32.o \
	$(obj).target/$(TARGET)/talk/base/diskcache.o \
	$(obj).target/$(TARGET)/talk/base/event.o \
	$(obj).target/$(TARGET)/talk/base/filelock.o \
	$(obj).target/$(TARGET)/talk/base/fileutils.o \
	$(obj).target/$(TARGET)/talk/base/firewallsocketserver.o \
	$(obj).target/$(TARGET)/talk/base/flags.o \
	$(obj).target/$(TARGET)/talk/base/helpers.o \
	$(obj).target/$(TARGET)/talk/base/host.o \
	$(obj).target/$(TARGET)/talk/base/httpbase.o \
	$(obj).target/$(TARGET)/talk/base/httpclient.o \
	$(obj).target/$(TARGET)/talk/base/httpcommon.o \
	$(obj).target/$(TARGET)/talk/base/httprequest.o \
	$(obj).target/$(TARGET)/talk/base/httpserver.o \
	$(obj).target/$(TARGET)/talk/base/ipaddress.o \
	$(obj).target/$(TARGET)/talk/base/json.o \
	$(obj).target/$(TARGET)/talk/base/logging.o \
	$(obj).target/$(TARGET)/talk/base/md5.o \
	$(obj).target/$(TARGET)/talk/base/messagedigest.o \
	$(obj).target/$(TARGET)/talk/base/messagehandler.o \
	$(obj).target/$(TARGET)/talk/base/messagequeue.o \
	$(obj).target/$(TARGET)/talk/base/multipart.o \
	$(obj).target/$(TARGET)/talk/base/natserver.o \
	$(obj).target/$(TARGET)/talk/base/natsocketfactory.o \
	$(obj).target/$(TARGET)/talk/base/nattypes.o \
	$(obj).target/$(TARGET)/talk/base/nethelpers.o \
	$(obj).target/$(TARGET)/talk/base/network.o \
	$(obj).target/$(TARGET)/talk/base/nssidentity.o \
	$(obj).target/$(TARGET)/talk/base/nssstreamadapter.o \
	$(obj).target/$(TARGET)/talk/base/optionsfile.o \
	$(obj).target/$(TARGET)/talk/base/pathutils.o \
	$(obj).target/$(TARGET)/talk/base/physicalsocketserver.o \
	$(obj).target/$(TARGET)/talk/base/proxydetect.o \
	$(obj).target/$(TARGET)/talk/base/proxyinfo.o \
	$(obj).target/$(TARGET)/talk/base/proxyserver.o \
	$(obj).target/$(TARGET)/talk/base/ratelimiter.o \
	$(obj).target/$(TARGET)/talk/base/ratetracker.o \
	$(obj).target/$(TARGET)/talk/base/sha1.o \
	$(obj).target/$(TARGET)/talk/base/sharedexclusivelock.o \
	$(obj).target/$(TARGET)/talk/base/signalthread.o \
	$(obj).target/$(TARGET)/talk/base/socketadapters.o \
	$(obj).target/$(TARGET)/talk/base/socketaddress.o \
	$(obj).target/$(TARGET)/talk/base/socketaddresspair.o \
	$(obj).target/$(TARGET)/talk/base/socketpool.o \
	$(obj).target/$(TARGET)/talk/base/socketstream.o \
	$(obj).target/$(TARGET)/talk/base/ssladapter.o \
	$(obj).target/$(TARGET)/talk/base/sslsocketfactory.o \
	$(obj).target/$(TARGET)/talk/base/sslidentity.o \
	$(obj).target/$(TARGET)/talk/base/sslstreamadapter.o \
	$(obj).target/$(TARGET)/talk/base/sslstreamadapterhelper.o \
	$(obj).target/$(TARGET)/talk/base/stream.o \
	$(obj).target/$(TARGET)/talk/base/stringencode.o \
	$(obj).target/$(TARGET)/talk/base/stringutils.o \
	$(obj).target/$(TARGET)/talk/base/systeminfo.o \
	$(obj).target/$(TARGET)/talk/base/task.o \
	$(obj).target/$(TARGET)/talk/base/taskparent.o \
	$(obj).target/$(TARGET)/talk/base/taskrunner.o \
	$(obj).target/$(TARGET)/talk/base/testclient.o \
	$(obj).target/$(TARGET)/talk/base/thread.o \
	$(obj).target/$(TARGET)/talk/base/timeutils.o \
	$(obj).target/$(TARGET)/talk/base/timing.o \
	$(obj).target/$(TARGET)/talk/base/transformadapter.o \
	$(obj).target/$(TARGET)/talk/base/urlencode.o \
	$(obj).target/$(TARGET)/talk/base/versionparsing.o \
	$(obj).target/$(TARGET)/talk/base/virtualsocketserver.o \
	$(obj).target/$(TARGET)/talk/base/worker.o \
	$(obj).target/$(TARGET)/talk/xmllite/qname.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlbuilder.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlconstants.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlelement.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlnsstack.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlparser.o \
	$(obj).target/$(TARGET)/talk/xmllite/xmlprinter.o \
	$(obj).target/$(TARGET)/talk/xmpp/chatroommoduleimpl.o \
	$(obj).target/$(TARGET)/talk/xmpp/constants.o \
	$(obj).target/$(TARGET)/talk/xmpp/discoitemsquerytask.o \
	$(obj).target/$(TARGET)/talk/xmpp/hangoutpubsubclient.o \
	$(obj).target/$(TARGET)/talk/xmpp/iqtask.o \
	$(obj).target/$(TARGET)/talk/xmpp/jid.o \
	$(obj).target/$(TARGET)/talk/xmpp/moduleimpl.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomconfigtask.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomdiscoverytask.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomlookuptask.o \
	$(obj).target/$(TARGET)/talk/xmpp/mucroomuniquehangoutidtask.o \
	$(obj).target/$(TARGET)/talk/xmpp/pingtask.o \
	$(obj).target/$(TARGET)/talk/xmpp/presenceouttask.o \
	$(obj).target/$(TARGET)/talk/xmpp/presencereceivetask.o \
	$(obj).target/$(TARGET)/talk/xmpp/presencestatus.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsubclient.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsub_task.o \
	$(obj).target/$(TARGET)/talk/xmpp/pubsubtasks.o \
	$(obj).target/$(TARGET)/talk/xmpp/receivetask.o \
	$(obj).target/$(TARGET)/talk/xmpp/rostermoduleimpl.o \
	$(obj).target/$(TARGET)/talk/xmpp/saslmechanism.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppclient.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppengineimpl.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppengineimpl_iq.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmpplogintask.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppstanzaparser.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmpptask.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppauth.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmpppump.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppsocket.o \
	$(obj).target/$(TARGET)/talk/xmpp/xmppthread.o \
	$(obj).target/$(TARGET)/talk/base/ifaddrs-android.o \
	$(obj).target/$(TARGET)/talk/base/linux.o \
	$(obj).target/$(TARGET)/talk/base/latebindingsymboltable.o \
	$(obj).target/$(TARGET)/talk/base/openssladapter.o \
	$(obj).target/$(TARGET)/talk/base/openssldigest.o \
	$(obj).target/$(TARGET)/talk/base/opensslidentity.o \
	$(obj).target/$(TARGET)/talk/base/opensslstreamadapter.o \
	$(obj).target/$(TARGET)/talk/base/posix.o \
	$(obj).target/$(TARGET)/talk/base/unixfilesystem.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	--sysroot=/home/richard/android-sdk/android-ndk-r8d/platforms/android-9/arch-arm \
	-Wl,--icf=safe \
	-L/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/stlport/libs/armeabi-v7a \
	-L/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi-v7a \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	--sysroot=/home/richard/android-sdk/android-ndk-r8d/platforms/android-9/arch-arm \
	-Wl,--icf=safe \
	-L/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/stlport/libs/armeabi-v7a \
	-L/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi-v7a \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	 \
	-lstlport_static \
	/home/richard/android-sdk/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/libgcc.a \
	-lc \
	-ldl \
	-lstdc++ \
	-lm

$(obj).target/talk/libjingle.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/talk/libjingle.a: LIBS := $(LIBS)
$(obj).target/talk/libjingle.a: TOOLSET := $(TOOLSET)
$(obj).target/talk/libjingle.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/talk/libjingle.a
# Add target alias
.PHONY: libjingle
libjingle: $(obj).target/talk/libjingle.a

# Add target alias to "all" target.
.PHONY: all
all: libjingle

# Add target alias
.PHONY: libjingle
libjingle: $(builddir)/libjingle.a

# Copy this to the static library output path.
$(builddir)/libjingle.a: TOOLSET := $(TOOLSET)
$(builddir)/libjingle.a: $(obj).target/talk/libjingle.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/libjingle.a
# Short alias for building this static library.
.PHONY: libjingle.a
libjingle.a: $(obj).target/talk/libjingle.a $(builddir)/libjingle.a

# Add static library to "all" target.
.PHONY: all
all: $(builddir)/libjingle.a

